### PR TITLE
Test Commit

### PR DESCRIPTION
**Pull request by pranjalkaler**
*Do Not Merge*

### CODE REVIEW

**Comment by pranjalkaler** [comment]
We are still getting option to merge the PR. Can we revoke that if the build fails?

**Comment by SaumyaSachdev** [comment]
https://docs.github.com/en/github/administering-a-repository/enabling-required-status-checks -- I don't see the Settings tab for this repo, maybe @vishalv971 you can make this change

**Comment by vishalv971** [comment]
> We are still getting the option to merge the PR. Can we revoke that if the build fails?
> Do we need this also?

I fix this  in repository permissions, thanks for highlighting

**Comment by vishalv971** [comment]
https://github.com/vishalv971/CompetitiveCoding/settings/branch_protection_rules/17390230

**Comment by vishalv971** [comment]
image
@pranjalkaler / @SaumyaSachdev  Seems to work now. Thanks guys

**Comment by pranjalkaler** [comment]
Closing this PR then. Cheers!

**Pull request closed without merging**
