### PR TITLE
Browser History

### PR DESCRIPTION
**Pull request by pranjalkaler**
https://leetcode.com/problems/design-browser-history

### CODE REVIEW

**Comment by pranjalkaler** [comment]
https://github.com/vishalv971/CompetitiveCoding/pull/64/checks?check_run_id=1075510251

the new build script compiled all of the files. @vishalv971

**Comment by vishalv971** [comment]
Can you rebase and push, it's showing the merge commit.

**Comment by vishalv971** [comment]
> https://github.com/vishalv971/CompetitiveCoding/pull/64/checks?check_run_id=1075510251
> the new build script compiled all of the files. @vishalv971
> 
> I guess everytime we push a code, there is a new container where the build happens. If this is the case, then make file approach also won't work.

You've to rebase

**Review by vishalv971 — CHANGES_REQUESTED** [review]
Rebase and push

**Pull request merged**
